plt.plot(axis, zeros, '#000000')
plt.plot(zeros, axis, '#000000')
plt.plot(xs, Lagrange(xs), 'b-', label='Lagrange(x)')
plt.plot(xs, L0(xs), 'r-', label='$L_0(x)$')
plt.plot(xs, L1(xs), 'g-', label='$L_1(x)$')
plt.plot(xs, L2(xs), 'y-', label='$L_2(x)$')
plt.plot(xs, L3(xs), label='$L_3(x)$')
plt.legend()
plt.grid(color='#CCCCCC', linestyle=':')
plt.xlim(-0.2, (pi/2)+0.5)
plt.ylim(-0.5, 1.5)
plt.xlabel('x')
plt.ylabel('y', rotation=0)
# plt.show()
plt.savefig(r'2NA Assignments\Assignment 2\LagrangePlot.pgf')