plt.subplot(221)
plt.plot(time, q, 'b-')
plt.xlabel('time (s)')
plt.ylabel('angle (rad)')
plt.subplot(222)
plt.plot(time, p, 'b-')
plt.xlabel('time (s)')
plt.ylabel('angle (rad)')
plt.subplot(223)
plt.plot(q, p, 'b-')
plt.xlabel('angle (rad)')
plt.ylabel('velocity ($\\frac{rad}{s}$)')